extension=pdo_mysql.so
extension=mbstring.so
extension=openssl.so
extension=fileinfo.so
extension=bcmath.so
extension=ctype.so
extension=tokenizer.so
extension=xml.so
extension=dom.so

memory_limit=256M
max_execution_time=30
upload_max_filesize=10M
post_max_size=12M
